# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a46311f0d9aec9f85b7c1fff23e7751958b21ca4fa6459c566c7ee52674d87a2db746d7cf6c0afad58e11b83f3828c33c720a2bf6af3ba1f30c34d9a40d2eb0

test:
  secret_key_base: a29a3e8de073605d4029d93b8f50f43d837c77931a931e5eb4e733a91aa629e8e65fbe91db93710bd7858d3ed23bf27c949868650d454c21c901eb2dbbf6ff92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
